### ISSUE TITLE
Master Todo List

### ISSUE THREAD

**Issue by Techbot121** [PAC3-Server/notagain#32]
# Todo

## Server
- [x] rewrite/replace chat
- [x] more aowl pac commands
- [ ] rewrite or make our own crashsystems
- [ ] jrpg death notifications
- [x] steam friends based prop protection
- [ ] change to random map if server is empty and allow players to vote change for map

## Web
- [ ] Create a Loadingscreen
- - [ ] show basic server info (hostname, online players, mapname etc...)
- - [ ] cycling background/image switcher || [attempt1](https://github.com/PAC3-Server/LoadingScreen/blob/master/templates/pac-server/js/slideshow.js)
## Misc
- [ ] write more todos

**Comment by NanoAi** [comment]
What features are you looking for in a loading screen?

**Comment by Techbot121** [comment]
for now, just a simple background image switcher with basic server info stuff. [I've made a crappy bg switcher in js that loads the url from a .txt file](https://github.com/PAC3-Server/LoadingScreen/blob/master/templates/pac-server/js/slideshow.js) which does seem to do the job quite well, but I suppose there are better ways to do it, also we're trying to not over complicate things if possible and keep it simple.

**Comment by Techbot121** [comment]
moved to https://github.com/PAC3-Server/notagain/projects/2
